package com.model;

/**
 * TKehu generated by MyEclipse Persistence Tools
 */
//客户信息
public class TKehu implements java.io.Serializable
{

	// Fields

	private Integer kehuId;

	private String kehuName;

	private String kehuSex;

	private Integer kehuAge;

	private String kehuXueli;

	private String kehuZhiwei;

	private String kehuAddress;

	private String kehuTel;

	private String kehuEmail;

	private String kehuQq;
//	客户登录名
	private String kehuLoginName;
//	客户登录密码
	private String kehuLoginPw;

	private Integer kehuOrgId;
	
	private String type;

	private String del;
	
	private String kehuOrgName;

	// Constructors

	/** default constructor */
	public TKehu()
	{
	}

	/** full constructor */
	public TKehu(String kehuName, String kehuSex,
			Integer kehuAge, String kehuXueli, String kehuZhiwei,
			String kehuAddress, String kehuTel, String kehuEmail,
			String kehuQq, String kehuLoginName,
			String kehuLoginPw, Integer kehuOrgId, String del)
	{
		this.kehuName = kehuName;
		this.kehuSex = kehuSex;
		this.kehuAge = kehuAge;
		this.kehuXueli = kehuXueli;
		this.kehuZhiwei = kehuZhiwei;
		this.kehuAddress = kehuAddress;
		this.kehuTel = kehuTel;
		this.kehuEmail = kehuEmail;
		this.kehuQq = kehuQq;
		this.kehuLoginName = kehuLoginName;
		this.kehuLoginPw = kehuLoginPw;
		this.kehuOrgId = kehuOrgId;
		this.del = del;
	}

	// Property accessors

	public Integer getKehuId()
	{
		return this.kehuId;
	}

	public void setKehuId(Integer kehuId)
	{
		this.kehuId = kehuId;
	}

	public String getKehuName()
	{
		return this.kehuName;
	}

	public void setKehuName(String kehuName)
	{
		this.kehuName = kehuName;
	}

	public String getKehuSex()
	{
		return this.kehuSex;
	}

	public void setKehuSex(String kehuSex)
	{
		this.kehuSex = kehuSex;
	}

	public Integer getKehuAge()
	{
		return this.kehuAge;
	}

	public void setKehuAge(Integer kehuAge)
	{
		this.kehuAge = kehuAge;
	}

	public String getKehuXueli()
	{
		return this.kehuXueli;
	}

	public void setKehuXueli(String kehuXueli)
	{
		this.kehuXueli = kehuXueli;
	}

	public String getKehuZhiwei()
	{
		return this.kehuZhiwei;
	}

	public void setKehuZhiwei(String kehuZhiwei)
	{
		this.kehuZhiwei = kehuZhiwei;
	}

	public String getKehuAddress()
	{
		return this.kehuAddress;
	}

	public void setKehuAddress(String kehuAddress)
	{
		this.kehuAddress = kehuAddress;
	}

	public String getKehuTel()
	{
		return this.kehuTel;
	}

	public void setKehuTel(String kehuTel)
	{
		this.kehuTel = kehuTel;
	}

	public String getType()
	{
		return type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	public String getKehuEmail()
	{
		return this.kehuEmail;
	}

	public void setKehuEmail(String kehuEmail)
	{
		this.kehuEmail = kehuEmail;
	}

	public String getKehuQq()
	{
		return this.kehuQq;
	}

	public void setKehuQq(String kehuQq)
	{
		this.kehuQq = kehuQq;
	}

	public String getKehuLoginName()
	{
		return this.kehuLoginName;
	}

	public void setKehuLoginName(String kehuLoginName)
	{
		this.kehuLoginName = kehuLoginName;
	}

	public String getKehuLoginPw()
	{
		return this.kehuLoginPw;
	}

	public void setKehuLoginPw(String kehuLoginPw)
	{
		this.kehuLoginPw = kehuLoginPw;
	}

	public Integer getKehuOrgId()
	{
		return this.kehuOrgId;
	}

	public void setKehuOrgId(Integer kehuOrgId)
	{
		this.kehuOrgId = kehuOrgId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getKehuOrgName()
	{
		return kehuOrgName;
	}

	public void setKehuOrgName(String kehuOrgName)
	{
		this.kehuOrgName = kehuOrgName;
	}

}